### ISSUE TITLE
Ruby group capstone: set up your Kanban board

### ISSUE THREAD

**Issue by williamscch** [AbrahaKahsay/catalogue-my-things#25]
[Kanban Board Link](https://github.com/AbrahaKahsay/catalogue-my-things/projects/1)

### We are 3 people on the team for this capstone

> Team member #1: @williamscch 

> Team member #2: @AbrahaKahsay 

> Team member #3: @aizjicod

**Comment by FrederickMih** [comment]
Hi @Team, 

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!


## Highlights

- Correct information is provided in the GitHub issue :heavy_check_mark: 

## Required Changes ♻️

- [x] Hi team, a student(@AbrahaKahsay) has a significant difference in the number of points (difference >= 5 points) more points than other members. Let's kindly make sure that the number of points is equally distributed among members.

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
